### ISSUE TITLE
Refactoring and testing

### ISSUE THREAD

**Issue by Kuyantsev-VP** [rvadim/elastalert-k8s-automation#19]
Refactoring is needed in order to simplify main file and split functions on different modules.
- Take out functions for reading configuration files into classes:
--  `LocalConfigReader` for reading configs in local environment. Initialized by local path to user configurations.
-- `RemoteConfigReader` for reading configs in Kubernetes namespaces. Initialized by Kubernetes cluster configuration.
- Take out functions for generating configurations via jinja templates into special class `Renderer`
- Test created entities.

**Comment by rvadim** [comment]
#17 merged

**Comment by Kuyantsev-VP** [comment]
Test description:
Test data added in project for tests below. This data includes two valid and one invalid user configuration.
- Test for LocalConfigReader: 
Read test data and check if only two configurations passes validation.
- Test for RemoteConfigReader:
Test data is added in mock object to make it configmap-like. Then mock object is provided to RemoteConfigParser. Test checks if only two configurations passes validation.
- Test for generators:
As soon as there is no need to check generation itself I decided to check if generated configurations can be parsed as yaml file. Test data described before is provided to LocalConfigReader and then to generator. Generator results are parsed with yaml.safe_load. Test fails if any exception occures during parsing generated files.
